// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AddProductReviewData,
  AddProductReviewErrors,
  AddProductReviewResponses,
  AddToCartData,
  AddToCartErrors,
  AddToCartResponses,
  AddToWishlistData,
  AddToWishlistErrors,
  AddToWishlistResponses,
  CreateOrderData,
  CreateOrderErrors,
  CreateOrderResponses,
  GetCartData,
  GetCartResponses,
  GetCategoryData,
  GetCategoryErrors,
  GetCategoryProductsData,
  GetCategoryProductsErrors,
  GetCategoryProductsResponses,
  GetCategoryResponses,
  GetDemoProductsData,
  GetDemoProductsResponses,
  GetOrderData,
  GetOrderErrors,
  GetOrderResponses,
  GetProductData,
  GetProductErrors,
  GetProductResponses,
  GetProductReviewsData,
  GetProductReviewsErrors,
  GetProductReviewsResponses,
  GetSubCategoryData,
  GetSubCategoryErrors,
  GetSubCategoryResponses,
  GetUserProfileData,
  GetUserProfileResponses,
  GetUserReviewsData,
  GetUserReviewsErrors,
  GetUserReviewsResponses,
  GetWishlistData,
  GetWishlistResponses,
  ListCategoriesData,
  ListCategoriesResponses,
  ListOrdersByUserData,
  ListOrdersByUserErrors,
  ListOrdersByUserResponses,
  ListOrdersData,
  ListOrdersResponses,
  ListProductsData,
  ListProductsErrors,
  ListProductsResponses,
  ListSubCategoriesData,
  ListSubCategoriesErrors,
  ListSubCategoriesResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  RegisterData,
  RegisterErrors,
  RegisterResponses,
  RemoveFromCartData,
  RemoveFromCartErrors,
  RemoveFromCartResponses,
  RemoveFromWishlistData,
  RemoveFromWishlistErrors,
  RemoveFromWishlistResponses,
  SearchProductsData,
  SearchProductsErrors,
  SearchProductsResponses,
  UpdateUserProfileData,
  UpdateUserProfileErrors,
  UpdateUserProfileResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Register a new user
 *
 * Create a new account with email, password, and full name. Returns a JWT access token on success. Returns 400 if the email is already registered.
 */
export const register = <ThrowOnError extends boolean = false>(
  options: Options<RegisterData, ThrowOnError>
) =>
  (options.client ?? client).post<RegisterResponses, RegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Login and get a JWT token
 *
 * Authenticate with email and password. Returns a JWT access token valid for 30 minutes. Send this token in the Authorization header as 'Bearer <token>' for all protected endpoints. Returns 401 if credentials are invalid.
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get current user profile
 *
 * Returns the profile of the currently authenticated user including saved address. Requires a valid Bearer token. Returns 401 if the token is missing or invalid.
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserProfileData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetUserProfileResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/profile',
    ...options,
  });

/**
 * Update current user profile
 *
 * Updates the authenticated user's profile fields (name, phone, address). Only provided fields are updated. Requires a valid Bearer token.
 */
export const updateUserProfile = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserProfileData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateUserProfileResponses, UpdateUserProfileErrors, ThrowOnError>(
    {
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/users/profile',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    }
  );

/**
 * List products with optional filtering and pagination
 *
 * Returns a paginated list of products with total count. Filter by subcategory_id, category_id, price range, or minimum rating. No authentication required.
 */
export const listProducts = <ThrowOnError extends boolean = false>(
  options?: Options<ListProductsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListProductsResponses, ListProductsErrors, ThrowOnError>({
    url: '/products/',
    ...options,
  });

/**
 * Get 10 demo products
 *
 * Returns 10 products picked across different categories. No pagination, no filters. Useful for landing pages or quick previews. No authentication required.
 */
export const getDemoProducts = <ThrowOnError extends boolean = false>(
  options?: Options<GetDemoProductsData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetDemoProductsResponses, unknown, ThrowOnError>({
    url: '/products/demo',
    ...options,
  });

/**
 * Search products by name or description
 *
 * Searches products where the name or description contains the query string (case-insensitive). Supports price range filtering. No authentication required.
 */
export const searchProducts = <ThrowOnError extends boolean = false>(
  options: Options<SearchProductsData, ThrowOnError>
) =>
  (options.client ?? client).get<SearchProductsResponses, SearchProductsErrors, ThrowOnError>({
    url: '/products/search',
    ...options,
  });

/**
 * Get a single product by ID
 *
 * Returns full details of a single product including its category, subcategory, price, rating, stock, and image URL. No authentication required. Returns 404 if the product does not exist.
 */
export const getProduct = <ThrowOnError extends boolean = false>(
  options: Options<GetProductData, ThrowOnError>
) =>
  (options.client ?? client).get<GetProductResponses, GetProductErrors, ThrowOnError>({
    url: '/products/{product_id}',
    ...options,
  });

/**
 * Get the current user's cart
 *
 * Returns all items in the authenticated user's shopping cart. Each item includes full product details. Requires a valid Bearer token.
 */
export const getCart = <ThrowOnError extends boolean = false>(
  options?: Options<GetCartData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetCartResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cart/',
    ...options,
  });

/**
 * Add a product to cart
 *
 * Adds a product to the authenticated user's cart. If the product is already in the cart, the quantity is increased by the given amount. Requires a valid Bearer token. Returns 404 if the product does not exist.
 */
export const addToCart = <ThrowOnError extends boolean = false>(
  options: Options<AddToCartData, ThrowOnError>
) =>
  (options.client ?? client).post<AddToCartResponses, AddToCartErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cart/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove an item from cart
 *
 * Removes a cart item by its cart item ID (not the product ID). The item must belong to the authenticated user. Requires a valid Bearer token. Returns 404 if the cart item is not found.
 */
export const removeFromCart = <ThrowOnError extends boolean = false>(
  options: Options<RemoveFromCartData, ThrowOnError>
) =>
  (options.client ?? client).delete<RemoveFromCartResponses, RemoveFromCartErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cart/{item_id}',
    ...options,
  });

/**
 * List all orders for the current user
 *
 * Returns all orders placed by the authenticated user, newest first, including items, shipping details, and status.
 */
export const listOrders = <ThrowOnError extends boolean = false>(
  options?: Options<ListOrdersData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListOrdersResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orders/',
    ...options,
  });

/**
 * Create an order
 *
 * Creates a new order for the authenticated user. If **items** is provided in the request body, the order is built directly from those items (direct order flow). If **items** is omitted, all products in the user's cart are used and the cart is cleared after the order is placed (checkout flow). Returns 400 if no items are provided and the cart is empty. Returns 404 if any specified product_id does not exist.
 */
export const createOrder = <ThrowOnError extends boolean = false>(
  options: Options<CreateOrderData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateOrderResponses, CreateOrderErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orders/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * List all orders for a given user
 *
 * Returns all orders placed by the specified user, newest first. Requires authentication.
 */
export const listOrdersByUser = <ThrowOnError extends boolean = false>(
  options: Options<ListOrdersByUserData, ThrowOnError>
) =>
  (options.client ?? client).get<ListOrdersByUserResponses, ListOrdersByUserErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orders/user/{user_id}',
    ...options,
  });

/**
 * Get a single order
 *
 * Returns the full details of a specific order belonging to the authenticated user. Returns 404 if the order does not exist or belongs to another user.
 */
export const getOrder = <ThrowOnError extends boolean = false>(
  options: Options<GetOrderData, ThrowOnError>
) =>
  (options.client ?? client).get<GetOrderResponses, GetOrderErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/orders/{order_id}',
    ...options,
  });

/**
 * List all categories
 *
 * Returns all product categories with their image. No authentication required.
 */
export const listCategories = <ThrowOnError extends boolean = false>(
  options?: Options<ListCategoriesData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListCategoriesResponses, unknown, ThrowOnError>({
    url: '/categories/',
    ...options,
  });

/**
 * Get a category with its subcategories
 *
 * Returns a single category along with all its subcategories. No authentication required. Returns 404 if the category does not exist.
 */
export const getCategory = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoryData, ThrowOnError>
) =>
  (options.client ?? client).get<GetCategoryResponses, GetCategoryErrors, ThrowOnError>({
    url: '/categories/{category_id}',
    ...options,
  });

/**
 * Get all products for a category
 *
 * Returns a paginated list of all products belonging to the given category (via its subcategories). Returns 404 if the category does not exist. No authentication required.
 */
export const getCategoryProducts = <ThrowOnError extends boolean = false>(
  options: Options<GetCategoryProductsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetCategoryProductsResponses,
    GetCategoryProductsErrors,
    ThrowOnError
  >({ url: '/categories/{category_id}/products', ...options });

/**
 * List subcategories with optional category filter
 *
 * Returns subcategories. Optionally filter by category_id to get subcategories of a specific category. No authentication required.
 */
export const listSubCategories = <ThrowOnError extends boolean = false>(
  options?: Options<ListSubCategoriesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListSubCategoriesResponses,
    ListSubCategoriesErrors,
    ThrowOnError
  >({ url: '/subcategories/', ...options });

/**
 * Get a subcategory with all its products
 *
 * Returns a single subcategory along with all products that belong to it. No authentication required. Returns 404 if the subcategory does not exist.
 */
export const getSubCategory = <ThrowOnError extends boolean = false>(
  options: Options<GetSubCategoryData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSubCategoryResponses, GetSubCategoryErrors, ThrowOnError>({
    url: '/subcategories/{subcategory_id}',
    ...options,
  });

/**
 * Get the current user's wishlist
 *
 * Returns all products in the authenticated user's wishlist. Each item includes full product details. Requires a valid Bearer token.
 */
export const getWishlist = <ThrowOnError extends boolean = false>(
  options?: Options<GetWishlistData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetWishlistResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/wishlist/',
    ...options,
  });

/**
 * Add a product to wishlist
 *
 * Adds a product to the authenticated user's wishlist. If the product is already in the wishlist, returns 400. Requires a valid Bearer token. Returns 404 if the product does not exist.
 */
export const addToWishlist = <ThrowOnError extends boolean = false>(
  options: Options<AddToWishlistData, ThrowOnError>
) =>
  (options.client ?? client).post<AddToWishlistResponses, AddToWishlistErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/wishlist/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Remove a product from wishlist
 *
 * Removes a product from the authenticated user's wishlist by product ID. Requires a valid Bearer token. Returns 404 if the product is not in the wishlist.
 */
export const removeFromWishlist = <ThrowOnError extends boolean = false>(
  options: Options<RemoveFromWishlistData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    RemoveFromWishlistResponses,
    RemoveFromWishlistErrors,
    ThrowOnError
  >({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/wishlist/{product_id}',
    ...options,
  });

/**
 * Get reviews for a product
 *
 * Returns all reviews for the given product ordered by newest first, each including the reviewer's user_id and name. No authentication required. Returns 404 if the product does not exist.
 */
export const getProductReviews = <ThrowOnError extends boolean = false>(
  options: Options<GetProductReviewsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetProductReviewsResponses, GetProductReviewsErrors, ThrowOnError>(
    { url: '/products/{product_id}/reviews', ...options }
  );

/**
 * Add a review for a product
 *
 * Adds a review for the given product mapped to the authenticated user. Response includes user_id and reviewer name. Authentication required. Returns 404 if the product does not exist.
 */
export const addProductReview = <ThrowOnError extends boolean = false>(
  options: Options<AddProductReviewData, ThrowOnError>
) =>
  (options.client ?? client).post<AddProductReviewResponses, AddProductReviewErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/products/{product_id}/reviews',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get all reviews written by a user
 *
 * Returns all reviews submitted by the given user, newest first, each including the product_id and product name. No authentication required. Returns 404 if the user does not exist.
 */
export const getUserReviews = <ThrowOnError extends boolean = false>(
  options: Options<GetUserReviewsData, ThrowOnError>
) =>
  (options.client ?? client).get<GetUserReviewsResponses, GetUserReviewsErrors, ThrowOnError>({
    url: '/users/{user_id}/reviews',
    ...options,
  });
