// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://ecom-api-956506160468.us-central1.run.app' | (string & {});
};

/**
 * CartItemAdd
 */
export type CartItemAdd = {
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Quantity
   */
  quantity?: number;
};

/**
 * CartItemOut
 */
export type CartItemOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Quantity
   */
  quantity: number;
  product: ProductOut;
};

/**
 * CategoryOut
 */
export type CategoryOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Image Url
   */
  image_url?: string;
};

/**
 * CategoryWithSubCategories
 */
export type CategoryWithSubCategories = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Image Url
   */
  image_url?: string;
  /**
   * Subcategories
   */
  subcategories?: Array<SubCategoryOut>;
};

/**
 * CreateOrderRequest
 */
export type CreateOrderRequest = {
  /**
   * Shipping Name
   */
  shipping_name: string;
  /**
   * Shipping Email
   */
  shipping_email: string;
  /**
   * Shipping Phone
   */
  shipping_phone: string;
  /**
   * Shipping Address
   */
  shipping_address: string;
  /**
   * Shipping City
   */
  shipping_city: string;
  /**
   * Shipping State
   */
  shipping_state: string;
  /**
   * Shipping Zip
   */
  shipping_zip: string;
  /**
   * Shipping Country
   */
  shipping_country?: string;
  /**
   * Total
   *
   * Frontend-calculated order total (used for cart/checkout flow). If omitted, total is derived from item unit_prices.
   */
  total?: number | null;
  /**
   * Items
   *
   * Explicit list of items to order. If omitted, the user's cart is used (checkout flow) and cleared after the order is placed.
   */
  items?: Array<OrderItemIn> | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 */
export type LoginRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
};

/**
 * OrderItemIn
 */
export type OrderItemIn = {
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Quantity
   *
   * Quantity of the product.
   */
  quantity?: number;
  /**
   * Unit Price
   *
   * Final unit price after all frontend calculations (tax, discount, etc.).
   */
  unit_price: number;
};

/**
 * OrderItemOut
 */
export type OrderItemOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Quantity
   */
  quantity: number;
  /**
   * Price
   */
  price: number;
  /**
   * Product Name
   */
  product_name?: string;
  /**
   * Product Image
   */
  product_image?: string;
};

/**
 * OrderOut
 */
export type OrderOut = {
  /**
   * Id
   */
  id: number;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Total
   */
  total: number;
  /**
   * Status
   */
  status: string;
  /**
   * Created At
   */
  created_at: string;
  /**
   * Shipping Name
   */
  shipping_name?: string;
  /**
   * Shipping Email
   */
  shipping_email?: string;
  /**
   * Shipping Phone
   */
  shipping_phone?: string;
  /**
   * Shipping Address
   */
  shipping_address?: string;
  /**
   * Shipping City
   */
  shipping_city?: string;
  /**
   * Shipping State
   */
  shipping_state?: string;
  /**
   * Shipping Zip
   */
  shipping_zip?: string;
  /**
   * Shipping Country
   */
  shipping_country?: string;
  /**
   * Items
   */
  items: Array<OrderItemOut>;
};

/**
 * PaginatedProducts
 */
export type PaginatedProducts = {
  /**
   * Items
   *
   * List of products for the current page.
   */
  items: Array<ProductOut>;
  /**
   * Total
   *
   * Total number of products matching the query.
   */
  total: number;
  /**
   * Skip
   *
   * Number of products skipped.
   */
  skip: number;
  /**
   * Limit
   *
   * Page size used for this response.
   */
  limit: number;
};

/**
 * ProductOut
 */
export type ProductOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Price
   */
  price: number;
  /**
   * Original Price
   */
  original_price?: number | null;
  /**
   * Rating
   */
  rating?: number;
  /**
   * Review Count
   */
  review_count?: number;
  /**
   * Brand
   */
  brand?: string;
  /**
   * Image Url
   */
  image_url?: string;
  /**
   * Stock
   */
  stock: number;
  /**
   * Subcategory Id
   */
  subcategory_id: number;
  /**
   * Subcategory Name
   */
  subcategory_name?: string;
  /**
   * Category Name
   */
  category_name?: string;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
  /**
   * Email
   */
  email: string;
  /**
   * Password
   */
  password: string;
  /**
   * Full Name
   */
  full_name: string;
};

/**
 * ReviewCreate
 */
export type ReviewCreate = {
  /**
   * Rating
   *
   * Rating between 1 and 5.
   */
  rating: number;
  /**
   * Review Text
   *
   * Review body text.
   */
  review_text: string;
};

/**
 * ReviewOut
 */
export type ReviewOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  /**
   * Product Name
   */
  product_name?: string;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Reviewer Name
   */
  reviewer_name?: string;
  /**
   * Rating
   */
  rating: number;
  /**
   * Review Text
   */
  review_text: string;
  /**
   * Created At
   */
  created_at: string;
};

/**
 * SubCategoryOut
 */
export type SubCategoryOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Image Url
   */
  image_url?: string;
  /**
   * Category Id
   */
  category_id: number;
};

/**
 * SubCategoryWithProducts
 */
export type SubCategoryWithProducts = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string;
  /**
   * Image Url
   */
  image_url?: string;
  /**
   * Category Id
   */
  category_id: number;
  /**
   * Products
   */
  products?: Array<ProductOut>;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
  /**
   * Access Token
   */
  access_token: string;
  /**
   * Token Type
   */
  token_type?: string;
};

/**
 * UserOut
 */
export type UserOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Email
   */
  email: string;
  /**
   * Full Name
   */
  full_name: string;
  /**
   * Is Active
   */
  is_active: boolean;
  /**
   * Phone
   */
  phone?: string;
  /**
   * Address
   */
  address?: string;
  /**
   * City
   */
  city?: string;
  /**
   * State
   */
  state?: string;
  /**
   * Zip Code
   */
  zip_code?: string;
  /**
   * Country
   */
  country?: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
  /**
   * Full Name
   */
  full_name?: string | null;
  /**
   * Phone
   */
  phone?: string | null;
  /**
   * Address
   */
  address?: string | null;
  /**
   * City
   */
  city?: string | null;
  /**
   * State
   */
  state?: string | null;
  /**
   * Zip Code
   */
  zip_code?: string | null;
  /**
   * Country
   */
  country?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

/**
 * WishlistItemAdd
 */
export type WishlistItemAdd = {
  /**
   * Product Id
   */
  product_id: number;
};

/**
 * WishlistItemOut
 */
export type WishlistItemOut = {
  /**
   * Id
   */
  id: number;
  /**
   * Product Id
   */
  product_id: number;
  product: ProductOut;
};

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * Successful Response
   */
  201: TokenResponse;
};

export type RegisterResponse = RegisterResponses[keyof RegisterResponses];

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Successful Response
   */
  200: TokenResponse;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type GetUserProfileData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/users/profile';
};

export type GetUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserOut;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type UpdateUserProfileData = {
  body: UserUpdate;
  path?: never;
  query?: never;
  url: '/users/profile';
};

export type UpdateUserProfileErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserProfileError = UpdateUserProfileErrors[keyof UpdateUserProfileErrors];

export type UpdateUserProfileResponses = {
  /**
   * Successful Response
   */
  200: UserOut;
};

export type UpdateUserProfileResponse =
  UpdateUserProfileResponses[keyof UpdateUserProfileResponses];

export type ListProductsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip
     *
     * Number of products to skip for pagination.
     */
    skip?: number;
    /**
     * Limit
     *
     * Maximum number of products to return.
     */
    limit?: number;
    /**
     * Subcategory Id
     *
     * Filter by subcategory ID.
     */
    subcategory_id?: number | null;
    /**
     * Category Id
     *
     * Filter by category ID (returns products from all subcategories of this category).
     */
    category_id?: number | null;
    /**
     * Price Min
     *
     * Minimum price filter.
     */
    price_min?: number | null;
    /**
     * Price Max
     *
     * Maximum price filter.
     */
    price_max?: number | null;
    /**
     * Rating Min
     *
     * Minimum rating filter (0–5).
     */
    rating_min?: number | null;
  };
  url: '/products/';
};

export type ListProductsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListProductsError = ListProductsErrors[keyof ListProductsErrors];

export type ListProductsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedProducts;
};

export type ListProductsResponse = ListProductsResponses[keyof ListProductsResponses];

export type GetDemoProductsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/products/demo';
};

export type GetDemoProductsResponses = {
  /**
   * Response Getdemoproducts
   *
   * Successful Response
   */
  200: Array<ProductOut>;
};

export type GetDemoProductsResponse = GetDemoProductsResponses[keyof GetDemoProductsResponses];

export type SearchProductsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Q
     *
     * Search term. Matches against product name and description.
     */
    q: string;
    /**
     * Skip
     *
     * Number of products to skip for pagination.
     */
    skip?: number;
    /**
     * Limit
     *
     * Maximum number of products to return.
     */
    limit?: number;
    /**
     * Subcategory Id
     *
     * Optional. Narrow search to a specific subcategory.
     */
    subcategory_id?: number | null;
    /**
     * Price Min
     *
     * Minimum price filter.
     */
    price_min?: number | null;
    /**
     * Price Max
     *
     * Maximum price filter.
     */
    price_max?: number | null;
  };
  url: '/products/search';
};

export type SearchProductsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchProductsError = SearchProductsErrors[keyof SearchProductsErrors];

export type SearchProductsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedProducts;
};

export type SearchProductsResponse = SearchProductsResponses[keyof SearchProductsResponses];

export type GetProductData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: '/products/{product_id}';
};

export type GetProductErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProductError = GetProductErrors[keyof GetProductErrors];

export type GetProductResponses = {
  /**
   * Successful Response
   */
  200: ProductOut;
};

export type GetProductResponse = GetProductResponses[keyof GetProductResponses];

export type GetCartData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/cart/';
};

export type GetCartResponses = {
  /**
   * Response Getcart
   *
   * Successful Response
   */
  200: Array<CartItemOut>;
};

export type GetCartResponse = GetCartResponses[keyof GetCartResponses];

export type AddToCartData = {
  body: CartItemAdd;
  path?: never;
  query?: never;
  url: '/cart/';
};

export type AddToCartErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddToCartError = AddToCartErrors[keyof AddToCartErrors];

export type AddToCartResponses = {
  /**
   * Successful Response
   */
  201: CartItemOut;
};

export type AddToCartResponse = AddToCartResponses[keyof AddToCartResponses];

export type RemoveFromCartData = {
  body?: never;
  path: {
    /**
     * Item Id
     */
    item_id: number;
  };
  query?: never;
  url: '/cart/{item_id}';
};

export type RemoveFromCartErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveFromCartError = RemoveFromCartErrors[keyof RemoveFromCartErrors];

export type RemoveFromCartResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveFromCartResponse = RemoveFromCartResponses[keyof RemoveFromCartResponses];

export type ListOrdersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/orders/';
};

export type ListOrdersResponses = {
  /**
   * Response Listorders
   *
   * Successful Response
   */
  200: Array<OrderOut>;
};

export type ListOrdersResponse = ListOrdersResponses[keyof ListOrdersResponses];

export type CreateOrderData = {
  body: CreateOrderRequest;
  path?: never;
  query?: never;
  url: '/orders/';
};

export type CreateOrderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOrderError = CreateOrderErrors[keyof CreateOrderErrors];

export type CreateOrderResponses = {
  /**
   * Successful Response
   */
  201: OrderOut;
};

export type CreateOrderResponse = CreateOrderResponses[keyof CreateOrderResponses];

export type ListOrdersByUserData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/orders/user/{user_id}';
};

export type ListOrdersByUserErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListOrdersByUserError = ListOrdersByUserErrors[keyof ListOrdersByUserErrors];

export type ListOrdersByUserResponses = {
  /**
   * Response Listordersbyuser
   *
   * Successful Response
   */
  200: Array<OrderOut>;
};

export type ListOrdersByUserResponse = ListOrdersByUserResponses[keyof ListOrdersByUserResponses];

export type GetOrderData = {
  body?: never;
  path: {
    /**
     * Order Id
     */
    order_id: number;
  };
  query?: never;
  url: '/orders/{order_id}';
};

export type GetOrderErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrderError = GetOrderErrors[keyof GetOrderErrors];

export type GetOrderResponses = {
  /**
   * Successful Response
   */
  200: OrderOut;
};

export type GetOrderResponse = GetOrderResponses[keyof GetOrderResponses];

export type ListCategoriesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/categories/';
};

export type ListCategoriesResponses = {
  /**
   * Response Listcategories
   *
   * Successful Response
   */
  200: Array<CategoryOut>;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type GetCategoryData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: number;
  };
  query?: never;
  url: '/categories/{category_id}';
};

export type GetCategoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCategoryError = GetCategoryErrors[keyof GetCategoryErrors];

export type GetCategoryResponses = {
  /**
   * Successful Response
   */
  200: CategoryWithSubCategories;
};

export type GetCategoryResponse = GetCategoryResponses[keyof GetCategoryResponses];

export type GetCategoryProductsData = {
  body?: never;
  path: {
    /**
     * Category Id
     */
    category_id: number;
  };
  query?: {
    /**
     * Skip
     *
     * Number of products to skip for pagination.
     */
    skip?: number;
    /**
     * Limit
     *
     * Maximum number of products to return.
     */
    limit?: number;
  };
  url: '/categories/{category_id}/products';
};

export type GetCategoryProductsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCategoryProductsError = GetCategoryProductsErrors[keyof GetCategoryProductsErrors];

export type GetCategoryProductsResponses = {
  /**
   * Successful Response
   */
  200: PaginatedProducts;
};

export type GetCategoryProductsResponse =
  GetCategoryProductsResponses[keyof GetCategoryProductsResponses];

export type ListSubCategoriesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category Id
     *
     * Filter by parent category ID.
     */
    category_id?: number | null;
  };
  url: '/subcategories/';
};

export type ListSubCategoriesErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ListSubCategoriesError = ListSubCategoriesErrors[keyof ListSubCategoriesErrors];

export type ListSubCategoriesResponses = {
  /**
   * Response Listsubcategories
   *
   * Successful Response
   */
  200: Array<SubCategoryOut>;
};

export type ListSubCategoriesResponse =
  ListSubCategoriesResponses[keyof ListSubCategoriesResponses];

export type GetSubCategoryData = {
  body?: never;
  path: {
    /**
     * Subcategory Id
     */
    subcategory_id: number;
  };
  query?: never;
  url: '/subcategories/{subcategory_id}';
};

export type GetSubCategoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSubCategoryError = GetSubCategoryErrors[keyof GetSubCategoryErrors];

export type GetSubCategoryResponses = {
  /**
   * Successful Response
   */
  200: SubCategoryWithProducts;
};

export type GetSubCategoryResponse = GetSubCategoryResponses[keyof GetSubCategoryResponses];

export type GetWishlistData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/wishlist/';
};

export type GetWishlistResponses = {
  /**
   * Response Getwishlist
   *
   * Successful Response
   */
  200: Array<WishlistItemOut>;
};

export type GetWishlistResponse = GetWishlistResponses[keyof GetWishlistResponses];

export type AddToWishlistData = {
  body: WishlistItemAdd;
  path?: never;
  query?: never;
  url: '/wishlist/';
};

export type AddToWishlistErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddToWishlistError = AddToWishlistErrors[keyof AddToWishlistErrors];

export type AddToWishlistResponses = {
  /**
   * Successful Response
   */
  201: WishlistItemOut;
};

export type AddToWishlistResponse = AddToWishlistResponses[keyof AddToWishlistResponses];

export type RemoveFromWishlistData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: '/wishlist/{product_id}';
};

export type RemoveFromWishlistErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RemoveFromWishlistError = RemoveFromWishlistErrors[keyof RemoveFromWishlistErrors];

export type RemoveFromWishlistResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type RemoveFromWishlistResponse =
  RemoveFromWishlistResponses[keyof RemoveFromWishlistResponses];

export type GetProductReviewsData = {
  body?: never;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: '/products/{product_id}/reviews';
};

export type GetProductReviewsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetProductReviewsError = GetProductReviewsErrors[keyof GetProductReviewsErrors];

export type GetProductReviewsResponses = {
  /**
   * Response Getproductreviews
   *
   * Successful Response
   */
  200: Array<ReviewOut>;
};

export type GetProductReviewsResponse =
  GetProductReviewsResponses[keyof GetProductReviewsResponses];

export type AddProductReviewData = {
  body: ReviewCreate;
  path: {
    /**
     * Product Id
     */
    product_id: number;
  };
  query?: never;
  url: '/products/{product_id}/reviews';
};

export type AddProductReviewErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type AddProductReviewError = AddProductReviewErrors[keyof AddProductReviewErrors];

export type AddProductReviewResponses = {
  /**
   * Successful Response
   */
  201: ReviewOut;
};

export type AddProductReviewResponse = AddProductReviewResponses[keyof AddProductReviewResponses];

export type GetUserReviewsData = {
  body?: never;
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: '/users/{user_id}/reviews';
};

export type GetUserReviewsErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserReviewsError = GetUserReviewsErrors[keyof GetUserReviewsErrors];

export type GetUserReviewsResponses = {
  /**
   * Response Getuserreviews
   *
   * Successful Response
   */
  200: Array<ReviewOut>;
};

export type GetUserReviewsResponse = GetUserReviewsResponses[keyof GetUserReviewsResponses];
